# Generated by Django 3.1.4 on 2021-01-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20210108_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('Serbia', 'Serbia'), ('Croatia', 'Croatia')], max_length=128),
        ),
    ]
